### ISSUE TITLE
Deployment Issue on Azure Pipeline - 'Cannot find module axios'

### ISSUE THREAD

**Issue by almedinaMezit** [ForgeRock/fr-config-manager#161]
Hello,

We are currently facing a deployment issue on our Azure Pipeline related to the ForgeRock Config Manager. The error message we are encountering is:

Error: Cannot find module 'axios'

We are using fr-config-pull.

Thank you

**Comment by christian-brindley** [comment]
Hi - did you run `npm install` (or `npm install --ws` for previous versions) as per the README?

**Comment by almedinaMezit** [comment]
Yes, and everything was working fine until Friday.

**Comment by christian-brindley** [comment]
The dependencies are now in the base package.json for ease of installing the tools as a whole. This means that when installing the individual packages via `npm link`, the dependencies are not installed properly. 

We will work on a fix for backward compatibility. In the meantime, workarounds include

- Explicitly checkout v1.4.0 before linking, instead of using the latest version - `git checkout v1.4.0` 
or 
- Run `npm install` and `npm link` from the root directory as per the latest README

**Comment by christian-brindley** [comment]
Another workaround

- In the root directory, instead of running `npm install --ws`, run `npm install` (without the `--ws` option)

**Comment by almedinaMezit** [comment]
Thank you very much.
I checked again readme file and updated pipeline with those instructions.
